name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Instalar dependências
        run: npm install

      - name: Instalar Cypress
        run: npx cypress install

      - name: Rodar testes do Cypress
        run: npm run cy:run 

      - name: Salvar screenshots e vídeos em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
